In [1]:
from quantumsparse.spin import SpinOperators
from quantumsparse.operator import Symmetry, Operator
from quantumsparse.spin.shift import shift, shift_foundamental
from quantumsparse.spin import Heisenberg
from quantumsparse.spin.functions import rotate_spins
import numpy as np
from copy import deepcopy
import matplotlib.pyplot as plt

plt.style.use('../../notebook.mplstyle')                # use matplotlib style notebook.mplstyle

In [2]:
S     = 1./2. # spin value
Nsites = 4 # number of sites
spin_values = np.full(Nsites,S)

In [ ]:
T = shift_foundamental(Nsites)
T

In [5]:
Tnew = T.copy()

In [8]:
Tnew.diagonalize()

	n_components: 1
	eigensolution test: 1.810512918042978e-15


AttributeError: 'numpy.ndarray' object has no attribute 'n_blocks'

In [73]:
r = np.linspace(0,1,Nsites,endpoint=False)
k = np.linspace(0,1,Nsites,endpoint=False)
vtest = np.exp(1.j*2*np.pi*np.outer(r,k)*Nsites)

In [74]:
vtest @ np.diag(roots_of_unity(Nsites))

array([[ 1.0000000e+00+0.00000000e+00j,  6.1232340e-17+1.00000000e+00j,
        -1.0000000e+00+1.22464680e-16j, -1.8369702e-16-1.00000000e+00j],
       [ 1.0000000e+00+0.00000000e+00j, -1.0000000e+00+1.22464680e-16j,
         1.0000000e+00-2.44929360e-16j, -1.0000000e+00+3.67394040e-16j],
       [ 1.0000000e+00+0.00000000e+00j, -1.8369702e-16-1.00000000e+00j,
        -1.0000000e+00+3.67394040e-16j,  5.5109106e-16+1.00000000e+00j],
       [ 1.0000000e+00+0.00000000e+00j,  1.0000000e+00-2.44929360e-16j,
         1.0000000e+00-4.89858720e-16j,  1.0000000e+00-7.34788079e-16j]])

In [75]:
test = T @ vtest - vtest @ np.diag(roots_of_unity(Nsites))
test.imag

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 2.44929360e-16, 4.89858720e-16, 7.34788079e-16]])

In [76]:
np.round(vtest.imag,4)

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  1.,  0., -1.],
       [ 0.,  0., -0.,  0.],
       [ 0., -1.,  0.,  1.]])